# Set nginx base image
FROM nginx:alpine

# File Author / Maintainer
MAINTAINER ANO "Digital Country"

EXPOSE 80

RUN set -ex \
  && apk update \
  && apk --no-cache add \
    apk-tools

# For rc-service:
# apk add openrc

# For debug:
# apk add tcpdump bash gawk sed grep bc coreutils netcat-openbsd

RUN mkdir -p /run/nginx
RUN mkdir -p /app
RUN mkdir -p /cache

RUN chown nginx:nginx -R /app/
RUN chown nginx:nginx -R /cache/

VOLUME /app/
VOLUME /cache/

RUN apk --no-cache add \
            php5-fpm php5-mcrypt php5-soap php5-redis php5-openssl \
            php5-json php5-dom php5-zip php5-bcmath php5-gd \
            php5-xmlreader php5-xmlrpc php5-curl \
            php5-session php5-sodium php5-ldap \
            php5-pdo php5-pgsql php5-pdo_pgsql php5-mysql \
            php5-tokenizer composer \
            php5-ctype php5-xmlwriter \
            unzip zip \
            tzdata git

RUN mkdir -pv /var/data/static/
RUN chown nginx:nginx -R /var/data/
VOLUME /var/data/static/

ADD etc/php-fpm/www.conf /etc/php/php-fpm.d/www.conf
ADD etc/php-fpm/php.ini /etc/php/php.ini
ADD etc/nginx/default.conf /etc/nginx/conf.d/default.conf
ADD etc/nginx/fastcgi.conf /etc/nginx/fastcgi.conf

ADD ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

#RUN rc-update add nginx default
#RUN rc-update add php-fpm default

ENTRYPOINT ["sh","/entrypoint.sh"]
